export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const TOTAL_PRICE_OF_CART = "TOTAL_PRICE_OF_CART";
export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
export const SORT_PRICE = "SORT_PRICE";
export const SELECT_TYPE = "SELECT_TYPE";
